# Site settings
title: Ozan Yildiz
email:
description: > # this means to ignore newlines until "baseurl:"
  In this blog you will see mostly things about programming especially 
  on Python and other technologies that I am digging and want to say few 
  words about. Besides, some music maybe. Hope you enjoy reading it and find it useful.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ozanyyildiz
github_username:  ozanyildiz

# Build settings
markdown: kramdown
